@startuml quiz

class クイズ {
    + 合計点を計算する()
}

class 問題 {
    - 問題文
    - 制限時間
    - 配点
}

class 選択肢 {
    - 選択文
    - 正否
}

abstract 回答 {
    + 得点を出す()
}

class 回答あり {
    - 経過時間
}

class 回答なし {
}

クイズ *-- "1..10" 問題
問題 *-- "2..9" 選択肢
クイズ -- "0..10" 回答
問題 - 回答: < 出題内容
回答 <|-- 回答あり
回答 <|-- 回答なし
選択肢 - 回答あり: < 選択内容



@enduml