@startuml quiz

participant UI
participant クイズ
participant 回答
participant 問題

autonumber 1.1
UI -> クイズ: クイズの開始を要求する
activate クイズ
UI <-- クイズ: クイズを開始する
loop 出題数
    == 出題 ==
    UI -> クイズ: 問題を要求する
    クイズ -> 問題: 問題を生成する
    activate 問題
    クイズ <-- 問題: 問題
    deactivate 問題
    UI <-- クイズ: 問題
    == 回答 ==
    UI -> クイズ: 回答する
    クイズ -> 問題: 問題を取得する
    activate 問題
    クイズ <-- 問題: 問題
    クイズ -> 回答: 回答を生成する(問題)
    activate 回答
    クイズ -> 回答: 正否を判定する
    回答 -> 問題: 正解を取得する
    回答 <-- 問題: 選択肢
    クイズ <-- 回答: 判定結果
    UI <-- クイズ: 判定結果
end

autonumber 2.1
UI -> クイズ: 最終結果を要求する
loop 出題数
    クイズ -> 回答: 正否を判定する
    回答 -> 問題: 正解を取得する
    回答 <-- 問題: 選択肢
    クイズ <-- 回答: 判定結果
    クイズ -> 回答: 得点を出す
    回答 -> 問題: 配点を取得する
    回答 <-- 問題: 配点
    クイズ <-- 回答: 得点
end
deactivate 問題
deactivate 回答
UI <-- クイズ: 最終結果
note right: 最終結果は出題数、正解数、合計得点を返す

@enduml